/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.nio.file.Files;

// Imports for Swing
import javax.swing.DefaultListModel;

// Imports for error handling
import java.nio.file.NoSuchFileException;
import java.nio.file.Paths;
import java.io.*;

// Import all cookbook code
import ultimatecookbook.*;

/**
 *
 * @author Ethan Stewart
 */
public class EditRecipeUI extends ExtraWindow {

    /**
     * Creates new form EditRecipeUI
     */
    public EditRecipeUI() {
        // Call the superclass constructor 
        super();
        
        // Initialize Swing components
        initComponents();
    }
    
    public EditRecipeUI(Recipe r, String c) {   
        // Call the superclass constructor 
        super(c);
        
        // Initialize Swing components
        initComponents();
        
        // Save the old title
        this.oldTitle = r.getTitle();
        
        // Set the recipe values in the appropriate components
        this.editTitleTextField.setText(r.getTitle());
        this.jTextArea1.setText(r.getDirections());
        
        ((DefaultListModel) this.editIngList.getModel()).clear();
        for (String ingredient : r.getIngredients()) {
            ((DefaultListModel) this.editIngList.getModel()).addElement(ingredient);
        }
        // Make sure first ingredient is selected
        this.editIngList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editOKButton = new javax.swing.JButton();
        editCancelButton = new javax.swing.JButton();
        editTitleTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editIngList = new javax.swing.JList();
        addIngTextField = new javax.swing.JTextField();
        addIngButton = new javax.swing.JButton();
        editIngButton = new javax.swing.JButton();
        removeIngButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Recipe");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel7.setText("Title");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edit Recipe");

        editOKButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        editOKButton.setText("OK");
        editOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOKButtonActionPerformed(evt);
            }
        });

        editCancelButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        editCancelButton.setText("Cancel");
        editCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelButtonActionPerformed(evt);
            }
        });

        editTitleTextField.setEditable(false);
        editTitleTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel8.setText("Ingredients");

        editIngList.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        editIngList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(editIngList);

        addIngTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        addIngButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        addIngButton.setText("Add Ingredient");
        addIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngButtonActionPerformed(evt);
            }
        });

        editIngButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        editIngButton.setText("Edit Selected");
        editIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIngButtonActionPerformed(evt);
            }
        });

        removeIngButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        removeIngButton.setText("Remove Selected");
        removeIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeIngButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel10.setText("Directions");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editTitleTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addIngTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addIngButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(editIngButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeIngButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(editOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(editTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addIngTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addIngButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editIngButton)
                    .addComponent(removeIngButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOKButton)
                    .addComponent(editCancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOKButtonActionPerformed
        // Get the new values from the inputs
        String newTitle = editTitleTextField.getText();
        String newDirections = jTextArea1.getText();
        String[] newIngredients = new String[editIngList.getModel().getSize()];
        for (int i = 0; i < newIngredients.length; i++) {
            newIngredients[i] = (String) editIngList.getModel().getElementAt(i);
        }

        // Ensure no components are empty
        boolean canUpdate = true;
        if (newTitle == null || newTitle.length() <= 0) {
            this.setEnabled(false);
            new ErrorMessageUI("Title cannot\nbe empty", "Edit Recipe");
            canUpdate = false;
        }
        
        if (newDirections == null || newDirections.length() <= 0) {
            this.setEnabled(false);
            new ErrorMessageUI("Directions cannot\nbe empty", "Edit Recipe");
            canUpdate = false;
        }
        
        if (newIngredients.length <= 0) {
            this.setEnabled(false);
            new ErrorMessageUI("You must have at\nleast one ingredient", "Edit Recipe");
            canUpdate = false;
        }
        
        for (String ing : newIngredients) {
            if (ing == null || ing.length() <= 0) {
                this.setEnabled(false);
                new ErrorMessageUI("Blank ingredients\nnot permitted", "Edit Recipe");
                canUpdate = false;
            }
        }
        
        // If canCreate is still true, update the recipe
        if (canUpdate) {
            // Write the recipe to file
            Recipe r = new Recipe(newTitle, newIngredients, newDirections);
            r.writeRecipeToFile();
            
            // Update the recipe list in the main window
            for (Frame frame : Frame.getFrames()) {
                if (frame.getTitle().equals("Kitty's Cookbook")) {
                    ((UltimateCookBookUI) frame).addRecipesToViewList(Recipe.readAllRecipes());
                    ((UltimateCookBookUI) frame).setAllRecipes(Recipe.readAllRecipes());
                    ((UltimateCookBookUI) frame).resetRecipeViewer();
                    break;
                }
            }
            
            // Re-enable main window and close this one
            closeSecondaryFrame();
        }
    }//GEN-LAST:event_editOKButtonActionPerformed

    private void editCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelButtonActionPerformed
        closeSecondaryFrame();
    }//GEN-LAST:event_editCancelButtonActionPerformed

    private void addIngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngButtonActionPerformed
         // Get the value from the text field
        String ingToAdd = addIngTextField.getText();
        
        // If the value exists, add it to the list of ingredients 
        // and clear the text field
        if (ingToAdd != null && ingToAdd.length() > 0) {
            ((DefaultListModel) editIngList.getModel()).addElement(ingToAdd);
            addIngTextField.setText("");
        }
    }//GEN-LAST:event_addIngButtonActionPerformed

    private void editIngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIngButtonActionPerformed
        // Get the selected list item
        String selected = editIngList.getSelectedValue().toString();
        
        // Open the edit window
        this.setEnabled(false);
        new EditIngredientsUI(selected, "Edit Recipe").setVisible(true);
    }//GEN-LAST:event_editIngButtonActionPerformed

    private void removeIngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeIngButtonActionPerformed
        // Remove the selected element from the list
        ((DefaultListModel) editIngList.getModel()).removeElementAt(editIngList.getSelectedIndex());
    }//GEN-LAST:event_removeIngButtonActionPerformed

    public javax.swing.JList getEditIngList() {
        return editIngList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngButton;
    private javax.swing.JTextField addIngTextField;
    private javax.swing.JButton editCancelButton;
    private javax.swing.JButton editIngButton;
    private javax.swing.JList editIngList;
    private javax.swing.JButton editOKButton;
    private javax.swing.JTextField editTitleTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton removeIngButton;
    // End of variables declaration//GEN-END:variables

    // CUSTOM MEMBER VARIABLES
    private String oldTitle;
}
