/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

// Import for models (to update ingredients list)
import javax.swing.DefaultListModel;

/**
 *
 * @author Ethan Stewart
 */
public class EditIngredientsUI extends ExtraWindow {

    /**
     * Creates new form EditUI
     */
    public EditIngredientsUI() {
        // Call the superclass constructor 
        super();
        
        // Initialize Swing components
        initComponents();
        forSearch = false;
    }
    
    /**
     * Custom constructor to set the old value
     * @param old
     * @param frameTitle
     */
    public EditIngredientsUI(String old, String frameTitle) {
        // Call the superclass constructor 
        super(frameTitle);
        
        initComponents();
        jLabel8.setText(old);
        forSearch = false;
    }
    
    /**
     * Custom constructor to set the old value
     * @param old
     * @param frameTitle
     * @param search
     */
    public EditIngredientsUI(String old, String frameTitle, boolean search) {
        // Call the superclass constructor 
        super(frameTitle);
        
        initComponents();
        jLabel8.setText(old);
        forSearch = search;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newValueTextField = new javax.swing.JTextField();
        editOKButton = new javax.swing.JButton();
        editCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Ingredient");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel7.setText("New Value: ");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel8.setText("asdf");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel9.setText("Edit Ingredient");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel10.setText("Old Value: ");

        newValueTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        newValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newValueTextFieldActionPerformed(evt);
            }
        });

        editOKButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        editOKButton.setText("OK");
        editOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOKButtonActionPerformed(evt);
            }
        });

        editCancelButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        editCancelButton.setText("Cancel");
        editCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(newValueTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOKButton)
                    .addComponent(editCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void newValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newValueTextFieldActionPerformed

    private void editCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelButtonActionPerformed
        // Call method to re-enable main frame and close edit frame
        closeSecondaryFrame();
    }//GEN-LAST:event_editCancelButtonActionPerformed

    private void editOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOKButtonActionPerformed
        // Get the new value from the text field
        String newValue = newValueTextField.getText();

        if (newValue != null && newValue.length() > 0) {
            // Find the main frame
            for (Frame frame : Frame.getFrames()) {
                // Handle list change for main window
                if (frame.getTitle().equals("Kitty's Cookbook") && this.frameToAffect.equals("Kitty's Cookbook")) {
                    // Change the selected item in the list to the new value
                    javax.swing.JList mainList = this.forSearch ?
                            ((UltimateCookBookUI) frame).getSearchList() :
                            ((UltimateCookBookUI) frame).getCreateList();
                    DefaultListModel d = (DefaultListModel) mainList.getModel();
                    d.setElementAt(newValue, mainList.getSelectedIndex());
                    
                    // Re-enable the frame and stop the loop
                    frame.setEnabled(true);
                    break;
                }
                // Handle list change for recipe editing window
                else if (frame.getTitle().equals("Edit Recipe") && this.frameToAffect.equals("Edit Recipe")) {
                    // Change the selected item in the list to the new value
                    javax.swing.JList editList = ((EditRecipeUI) frame).getEditIngList();
                    DefaultListModel d = (DefaultListModel) editList.getModel();
                    d.setElementAt(newValue, editList.getSelectedIndex());
                    
                    // Re-enable the frame and stop the loop
                    frame.setEnabled(true);
                    break;
                }
            }

            // Close the editing window
            this.dispose();
        }
        else {
            this.setEnabled(false);
            new ErrorMessageUI("Empty value not\npermitted as ingredient", "Edit Ingredient");
        }
    }//GEN-LAST:event_editOKButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editCancelButton;
    private javax.swing.JButton editOKButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField newValueTextField;
    // End of variables declaration//GEN-END:variables

    // CUSTOM MEMBER VARIABLES
    private String frameToAffect;
    private boolean forSearch;
}
